name: Pascal CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Free Pascal Compiler
        run: sudo apt-get update && sudo apt-get install -y fp-compiler

      - name: Build Pascal Project
        run: fpc -XX sysblock.pas

      - name: Run tests
        run: ./sysblock
        
